import blockContent from './blockContent'
import category from './category'
import post from './post'
import author from './author'
import Home from './Home'
import projetos from './projetos'
import tecnologias from './tecnologias'
import skills from './skills'
import socialItems from './socialItems'
import geralBlog from './geralBlog'
import sidebarCards from './sidebarCards'
import newsletter from './newsletter'
import banner from './banner'

export const schemaTypes = [banner, sidebarCards, newsletter, socialItems, Home, skills, post, author, category, projetos, tecnologias, blockContent, geralBlog]
